"""create finance foundation

Revision ID: bfc163b9b8e9
Revises:
Create Date: 2026-09-16 13:20:39.515436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc163b9b8e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name=op.f('ck_account_currency_cny')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_table('activity_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_template'))
    )
    op.create_table('budget_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name=op.f('ck_budget_plan_currency_cny')),
    sa.CheckConstraint("timezone = 'Asia/Shanghai'", name=op.f('ck_budget_plan_timezone')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_plan'))
    )
    op.create_table('category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_normalized', sa.String(length=120), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('income','expense')", name=op.f('ck_category_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('kind', 'name_normalized', name='uq_category_kind_name_normalized')
    )
    op.create_table('command_receipt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('key_digest', sa.String(length=64), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('command_name', sa.String(length=80), nullable=False),
    sa.Column('result_type', sa.String(length=80), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_receipt')),
    sa.UniqueConstraint('source_system', 'key_digest', name='uq_command_receipt_source_digest')
    )
    op.create_table('income_schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_schedule'))
    )
    op.create_table('activity_template_revision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('reference_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name=op.f('ck_activity_template_revision_currency_cny')),
    sa.CheckConstraint('reference_minor IS NULL OR reference_minor >= 0', name=op.f('ck_activity_template_revision_reference_nonnegative')),
    sa.ForeignKeyConstraint(['template_id'], ['activity_template.id'], name=op.f('fk_activity_template_revision_template_id_activity_template'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_template_revision')),
    sa.UniqueConstraint('template_id', 'revision_no', name='uq_activity_template_revision_template_revision')
    )
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('activity_template') as batch_op:
            batch_op.create_foreign_key(
                'fk_activity_template_current_revision',
                'activity_template_revision', ['current_revision_id'], ['id']
            )
    else:
        op.create_foreign_key(
            'fk_activity_template_current_revision',
            'activity_template', 'activity_template_revision', ['current_revision_id'], ['id']
        )
    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('before_version', sa.Integer(), nullable=True),
    sa.Column('after_version', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['command_receipt_id'], ['command_receipt.id'], name=op.f('fk_audit_event_command_receipt_id_command_receipt'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_command_receipt_id'), ['command_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_id'), ['entity_id'], unique=False)

    op.create_table('budget_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('adjustment_reason', sa.String(length=240), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version_no > 0', name=op.f('ck_budget_version_version_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['budget_plan.id'], name=op.f('fk_budget_version_plan_id_budget_plan'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_version')),
    sa.UniqueConstraint('plan_id', 'period', 'version_no', name='uq_budget_version_plan_period_version')
    )
    with op.batch_alter_table('budget_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_version_period'), ['period'], unique=False)

    op.create_table('financial_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('related_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('relation_kind', sa.String(length=24), nullable=True),
    sa.Column('command_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name=op.f('ck_financial_transaction_currency_cny')),
    sa.CheckConstraint("kind IN ('opening_balance','income','expense','transfer','refund','reversal')", name=op.f('ck_financial_transaction_kind')),
    sa.CheckConstraint("relation_kind IS NULL OR relation_kind IN ('refund_of','reversal_of')", name=op.f('ck_financial_transaction_relation_kind')),
    sa.CheckConstraint("status = 'posted'", name=op.f('ck_financial_transaction_posted')),
    sa.ForeignKeyConstraint(['command_receipt_id'], ['command_receipt.id'], name=op.f('fk_financial_transaction_command_receipt_id_command_receipt'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['financial_transaction.id'], name=op.f('fk_financial_transaction_related_transaction_id_financial_transaction'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_transaction')),
    sa.UniqueConstraint('command_receipt_id', name=op.f('uq_financial_transaction_command_receipt_id'))
    )
    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_financial_transaction_occurred_at_kind', ['occurred_at', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_transaction_related_transaction_id'), ['related_transaction_id'], unique=False)

    op.create_table('income_schedule_version',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name=op.f('ck_income_schedule_version_currency_cny')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_income_schedule_version_amount_positive')),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name=op.f('ck_income_schedule_version_due_day')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_income_schedule_version_effective_range')),
    sa.ForeignKeyConstraint(['schedule_id'], ['income_schedule.id'], name=op.f('fk_income_schedule_version_schedule_id_income_schedule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_schedule_version')),
    sa.UniqueConstraint('schedule_id', 'revision_no', name='uq_income_schedule_version_schedule_revision')
    )
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('income_schedule') as batch_op:
            batch_op.create_foreign_key(
                'fk_income_schedule_current_version',
                'income_schedule_version', ['current_version_id'], ['id']
            )
    else:
        op.create_foreign_key(
            'fk_income_schedule_current_version',
            'income_schedule', 'income_schedule_version', ['current_version_id'], ['id']
        )
    op.create_table('activity_occurrence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_revision_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active','cancelled')", name=op.f('ck_activity_occurrence_status')),
    sa.ForeignKeyConstraint(['template_revision_id'], ['activity_template_revision.id'], name=op.f('fk_activity_occurrence_template_revision_id_activity_template_revision'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_occurrence'))
    )
    with op.batch_alter_table('activity_occurrence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_occurrence_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('budget_allocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('budget_version_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('limit_minor', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('limit_minor >= 0', name=op.f('ck_budget_allocation_limit_nonnegative')),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_version.id'], name=op.f('fk_budget_allocation_budget_version_id_budget_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_budget_allocation_category_id_category'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_allocation')),
    sa.UniqueConstraint('budget_version_id', 'category_id', name='uq_budget_allocation_version_category')
    )
    op.create_table('income_expectation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_version_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('expected_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','partial','matched')", name=op.f('ck_income_expectation_status')),
    sa.CheckConstraint('expected_minor > 0', name=op.f('ck_income_expectation_amount_positive')),
    sa.ForeignKeyConstraint(['schedule_version_id'], ['income_schedule_version.id'], name=op.f('fk_income_expectation_schedule_version_id_income_schedule_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_expectation')),
    sa.UniqueConstraint('schedule_version_id', 'due_date', name='uq_income_expectation_version_due_date')
    )
    with op.batch_alter_table('income_expectation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_expectation_due_date'), ['due_date'], unique=False)

    op.create_table('transaction_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('entry_role', sa.String(length=24), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(entry_role = 'account' AND account_id IS NOT NULL AND category_id IS NULL) OR (entry_role IN ('expense','income') AND account_id IS NULL AND category_id IS NOT NULL) OR (entry_role = 'opening_equity' AND account_id IS NULL AND category_id IS NULL)", name=op.f('ck_transaction_entry_target_shape')),
    sa.CheckConstraint("entry_role IN ('account','expense','income','opening_equity')", name=op.f('ck_transaction_entry_role')),
    sa.CheckConstraint('amount_minor <> 0', name=op.f('ck_transaction_entry_amount_nonzero')),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('fk_transaction_entry_account_id_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_transaction_entry_category_id_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['financial_transaction.id'], name=op.f('fk_transaction_entry_transaction_id_financial_transaction'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_entry')),
    sa.UniqueConstraint('transaction_id', 'line_no', name='uq_transaction_entry_transaction_line')
    )
    with op.batch_alter_table('transaction_entry', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_entry_account_transaction', ['account_id', 'transaction_id'], unique=False)
        batch_op.create_index('ix_transaction_entry_category_transaction', ['category_id', 'transaction_id'], unique=False)

    if op.get_bind().dialect.name == 'postgresql':
        op.execute("""
        CREATE FUNCTION finance_check_transaction_balance() RETURNS trigger AS $$
        DECLARE
            target_id uuid;
            entry_count bigint;
            entry_sum bigint;
        BEGIN
            IF TG_TABLE_NAME = 'financial_transaction' THEN
                target_id := COALESCE(NEW.id, OLD.id);
            ELSE
                target_id := COALESCE(NEW.transaction_id, OLD.transaction_id);
            END IF;
            IF EXISTS (SELECT 1 FROM financial_transaction WHERE id = target_id) THEN
                SELECT count(*), COALESCE(sum(amount_minor), 0)
                  INTO entry_count, entry_sum
                  FROM transaction_entry WHERE transaction_id = target_id;
                IF entry_count < 2 OR entry_sum <> 0 THEN
                    RAISE EXCEPTION 'unbalanced financial transaction'
                        USING ERRCODE = '23514', CONSTRAINT = 'ck_financial_transaction_balanced';
                END IF;
            END IF;
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)
        op.execute("""
        CREATE CONSTRAINT TRIGGER finance_transaction_balance_header
        AFTER INSERT OR UPDATE ON financial_transaction
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION finance_check_transaction_balance();
        """)
        op.execute("""
        CREATE CONSTRAINT TRIGGER finance_transaction_balance_entries
        AFTER INSERT OR UPDATE OR DELETE ON transaction_entry
        DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
        EXECUTE FUNCTION finance_check_transaction_balance();
        """)

    op.create_table('activity_entry_allocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_id', sa.Uuid(), nullable=False),
    sa.Column('expense_entry_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allocated_minor > 0', name=op.f('ck_activity_entry_allocation_amount_positive')),
    sa.ForeignKeyConstraint(['expense_entry_id'], ['transaction_entry.id'], name=op.f('fk_activity_entry_allocation_expense_entry_id_transaction_entry'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['occurrence_id'], ['activity_occurrence.id'], name=op.f('fk_activity_entry_allocation_occurrence_id_activity_occurrence'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_entry_allocation')),
    sa.UniqueConstraint('occurrence_id', 'expense_entry_id', name='uq_activity_allocation_occurrence_entry')
    )
    with op.batch_alter_table('activity_entry_allocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_entry_allocation_expense_entry_id'), ['expense_entry_id'], unique=False)

    op.create_table('income_expectation_match',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('expectation_id', sa.Uuid(), nullable=False),
    sa.Column('income_entry_id', sa.Uuid(), nullable=False),
    sa.Column('matched_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('matched_minor > 0', name=op.f('ck_income_expectation_match_amount_positive')),
    sa.ForeignKeyConstraint(['expectation_id'], ['income_expectation.id'], name=op.f('fk_income_expectation_match_expectation_id_income_expectation'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['income_entry_id'], ['transaction_entry.id'], name=op.f('fk_income_expectation_match_income_entry_id_transaction_entry'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_income_expectation_match')),
    sa.UniqueConstraint('income_entry_id', name=op.f('uq_income_expectation_match_income_entry_id'))
    )
    with op.batch_alter_table('income_expectation_match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_expectation_match_expectation_id'), ['expectation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('DROP TRIGGER IF EXISTS finance_transaction_balance_entries ON transaction_entry')
        op.execute('DROP TRIGGER IF EXISTS finance_transaction_balance_header ON financial_transaction')
        op.execute('DROP FUNCTION IF EXISTS finance_check_transaction_balance()')
    with op.batch_alter_table('income_expectation_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_expectation_match_expectation_id'))

    op.drop_table('income_expectation_match')
    with op.batch_alter_table('activity_entry_allocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_entry_allocation_expense_entry_id'))

    op.drop_table('activity_entry_allocation')
    with op.batch_alter_table('transaction_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_entry_category_transaction')
        batch_op.drop_index('ix_transaction_entry_account_transaction')

    op.drop_table('transaction_entry')
    with op.batch_alter_table('income_expectation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_expectation_due_date'))

    op.drop_table('income_expectation')
    op.drop_table('budget_allocation')
    with op.batch_alter_table('activity_occurrence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_occurrence_occurred_at'))

    op.drop_table('activity_occurrence')
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('income_schedule') as batch_op:
            batch_op.drop_constraint('fk_income_schedule_current_version', type_='foreignkey')
    else:
        op.drop_constraint('fk_income_schedule_current_version', 'income_schedule', type_='foreignkey')
    op.drop_table('income_schedule_version')
    with op.batch_alter_table('financial_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_transaction_related_transaction_id'))
        batch_op.drop_index('ix_financial_transaction_occurred_at_kind')

    op.drop_table('financial_transaction')
    with op.batch_alter_table('budget_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_version_period'))

    op.drop_table('budget_version')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_command_receipt_id'))

    op.drop_table('audit_event')
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('activity_template') as batch_op:
            batch_op.drop_constraint('fk_activity_template_current_revision', type_='foreignkey')
    else:
        op.drop_constraint('fk_activity_template_current_revision', 'activity_template', type_='foreignkey')
    op.drop_table('activity_template_revision')
    op.drop_table('income_schedule')
    op.drop_table('command_receipt')
    op.drop_table('category')
    op.drop_table('budget_plan')
    op.drop_table('activity_template')
    op.drop_table('account')
    # ### end Alembic commands ###
